CREATE DATABASE QLKETOAN
GO
USE QLKETOAN
GO

-----------------------------------------------------
CREATE TABLE BANHANG
(
MASPBH char(20) NOT NULL,
TENSP NVARCHAR(100) NOT NULL,
SOLUONG INT NOT NULL,
NGAYBAN DATE NOT NULL,
NGUOIBAN NVARCHAR(100) NOT NULL,
CONSTRAINT PK_MASPBH PRIMARY KEY(MASPBH)
)
INSERT INTO BANHANG VALUES ('SP01',N'Nước giải khát','200','12/05/2022',N'Nguyễn Văn Tùng');
INSERT INTO BANHANG VALUES ('SP02',N'Bánh kẹo','400','05/25/2022',N'Nguyễn Kim Sơn');


GO

SELECT * FROM BANHANG

CREATE PROCEDURE LOAD_BANHANG
AS
BEGIN
SELECT * FROM BANHANG
END
GO

DROP PROCEDURE LOAD_BANHANG

CREATE PROCEDURE INSERT_BANHANG
@MASPBH char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT,
@NGAYBAN DATE,
@NGUOIBAN NVARCHAR(100)
AS
BEGIN
INSERT INTO BANHANG(MASPBH,TENSP,SOLUONG,NGAYBAN,NGUOIBAN) VALUES(@MASPBH,@TENSP,@SOLUONG,@NGAYBAN,@NGUOIBAN)
END
GO

DROP PROCEDURE INSERT_BANHANG

CREATE PROCEDURE UPDATE_BANHANG
@MASPBH char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT,
@NGAYBAN DATE,
@NGUOIBAN NVARCHAR(100)
AS
BEGIN
UPDATE BANHANG SET MASPBH=@MASPBH,TENSP=@TENSP,SOLUONG=@SOLUONG,NGAYBAN=@NGAYBAN,NGUOIBAN=@NGUOIBAN WHERE MASPBH=@MASPBH
END
GO

DROP PROCEDURE UPDATE_BANHANG

CREATE PROCEDURE DELETE_BANHANG
@MASPBH char(20)
AS
BEGIN
DELETE FROM BANHANG WHERE MASPBH=@MASPBH
END
GO

DROP PROCEDURE DELETE_BANHANG

-------------------------------------------------------------
CREATE TABLE MUAHANG
(
MASPMH char(20) NOT NULL,
TENSP NVARCHAR(100) NOT NULL,
SOLUONG INT NOT NULL,
NGAYMUA DATE NOT NULL,
NGUOIMUA NVARCHAR(100) NOT NULL,
CONSTRAINT PK_MASPMH PRIMARY KEY(MASPMH)
)
INSERT INTO MUAHANG VALUES ('SP01',N'Nhiên liệu','600','04/05/2022',N'Nguyễn Trung Khải');
INSERT INTO MUAHANG VALUES ('SP02',N'Giấy','500','05/15/2022',N'Phạm Thành An');


GO

SELECT * FROM MUAHANG

CREATE PROCEDURE LOAD_MUAHANG
AS
BEGIN
SELECT * FROM MUAHANG
END
GO

CREATE PROCEDURE INSERT_MUAHANG
@MASPMH char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT,
@NGAYMUA DATE,
@NGUOIMUA NVARCHAR(100)
AS
BEGIN
INSERT INTO MUAHANG(MASPMH,TENSP,SOLUONG,NGAYMUA,NGUOIMUA) VALUES(@MASPMH,@TENSP,@SOLUONG,@NGAYMUA,@NGUOIMUA)
END
GO

CREATE PROCEDURE UPDATE_MUAHANG
@MASPMH char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT,
@NGAYMUA DATE,
@NGUOIMUA NVARCHAR(100)
AS
BEGIN
UPDATE MUAHANG SET MASPMH=@MASPMH,TENSP=@TENSP,SOLUONG=@SOLUONG,NGAYMUA=@NGAYMUA,NGUOIMUA=@NGUOIMUA WHERE MASPMH=@MASPMH
END
GO

CREATE PROCEDURE DELETE_MUAHANG
@MASPMH char(20)
AS
BEGIN
DELETE FROM MUAHANG WHERE MASPMH=@MASPMH
END
GO

CREATE PROCEDURE TIM_HANG
@TEN NVARCHAR(100)
AS
BEGIN
SELECT MUAHANG.MASPMH,MUAHANG.TENSP,MUAHANG.SOLUONG,MUAHANG.NGAYMUA,MUAHANG.NGUOIMUA
FROM MUAHANG
where MUAHANG.TENSP like '%'+@TEN+'%'
END
GO

-------------------------------------------------------------------
CREATE TABLE HDBANHANG
(
MAHD char(20),
TENSP NVARCHAR(100) NOT NULL,
SOLUONG INT NOT NULL,
NGAYBAN DATE NOT NULL,
NGUOIBAN NVARCHAR(100) NOT NULL,
GIA INT DEFAULT 0 NOT NULL,
TONG FLOAT DEFAULT 0 NOT NULL,
CONSTRAINT PK_MAHD PRIMARY KEY(MAHD)
)
INSERT INTO HDBANHANG VALUES ('HD01',N'Nước giải khát','600','04/05/2022',N'Nguyễn Trung Khải','','');
INSERT INTO HDBANHANG VALUES ('HD02',N'Đồ ăn nhanh','150','07/17/2021',N'Phạm An','','');

SELECT * FROM HDBANHANG

GO

CREATE PROCEDURE LOAD_HDBANHANG
AS
BEGIN
SELECT * FROM HDBANHANG
END
GO

CREATE PROCEDURE INSERT_HDBANHANG
@MAHD char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT,
@NGAYBAN DATE,
@NGUOIBAN NVARCHAR(100),
@GIA INT,
@TONG FLOAT
AS
BEGIN
INSERT INTO HDBANHANG(MAHD,TENSP,SOLUONG,NGAYBAN,NGUOIBAN,GIA,TONG) VALUES(@MAHD,@TENSP,@SOLUONG,@NGAYBAN,@NGUOIBAN,@GIA,@TONG)
END
GO

CREATE PROCEDURE UPDATE_HDBANHANG
@MAHD char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT,
@NGAYBAN DATE,
@NGUOIBAN NVARCHAR(100),
@GIA INT,
@TONG FLOAT
AS
BEGIN
UPDATE HDBANHANG SET MAHD=@MAHD,TENSP=@TENSP,SOLUONG=@SOLUONG,NGAYBAN=@NGAYBAN,NGUOIBAN=@NGUOIBAN,GIA=@GIA,TONG=@TONG WHERE MAHD=@MAHD
END
GO

CREATE PROCEDURE CANCEL_HDBANHANG
@MAHD char(20)
AS
BEGIN
DELETE FROM HDBANHANG WHERE MAHD=@MAHD
END
GO

CREATE PROCEDURE TIM_HDBH
@MAHD char(20)
AS
BEGIN
SELECT HDBANHANG.MAHD,HDBANHANG.TENSP,HDBANHANG.SOLUONG,HDBANHANG.NGAYBAN,HDBANHANG.NGUOIBAN,HDBANHANG.GIA ,HDBANHANG.TONG  FROM HDBANHANG
WHERE HDBANHANG.MAHD LIKE '%'+@MAHD+'%'
END
GO

-----------------------------------------------------------

CREATE TABLE HDMUAHANG
(
MAHDMH char(20),
TENSP NVARCHAR(100) NOT NULL,
SOLUONG INT NOT NULL,
NGAYMUA DATE NOT NULL,
NGUOIMUA NVARCHAR(100) NOT NULL,
GIA INT DEFAULT 0 NOT NULL,
TONG FLOAT DEFAULT 0 NOT NULL,
CONSTRAINT PK_MAHDMH PRIMARY KEY(MAHDMH)
)
INSERT INTO HDMUAHANG VALUES ('HD01',N'Nhu yếu phẩm','1000','12/05/2022',N'Nguyễn Trung Khải','','');
INSERT INTO HDMUAHANG VALUES ('HD02',N'Trang thiết bị','15','05/15/2022',N'Lý Thành Danh','','');

GO

SELECT * FROM HDMUAHANG

CREATE PROCEDURE LOAD_HDMUAHANG
AS
BEGIN
SELECT * FROM HDMUAHANG
END
GO

CREATE PROCEDURE INSERT_HDMUAHANG
@MAHDMH char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT,
@NGAYMUA DATE,
@NGUOIMUA NVARCHAR(100),
@GIA INT,
@TONG FLOAT
AS
BEGIN
INSERT INTO HDMUAHANG(MAHDMH,TENSP,SOLUONG,NGAYMUA,NGUOIMUA,GIA,TONG) VALUES(@MAHDMH,@TENSP,@SOLUONG,@NGAYMUA,@NGUOIMUA,@GIA,@TONG)
END
GO

CREATE PROCEDURE UPDATE_HDMUAHANG
@MAHDMH char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT,
@NGAYMUA DATE,
@NGUOIMUA NVARCHAR(100),
@GIA INT,
@TONG FLOAT
AS
BEGIN
UPDATE HDMUAHANG SET MAHDMH=@MAHDMH,TENSP=@TENSP,SOLUONG=@SOLUONG,NGAYMUA=@NGAYMUA,NGUOIMUA=@NGUOIMUA,GIA=@GIA,TONG=@TONG WHERE MAHDMH=@MAHDMH
END
GO

CREATE PROCEDURE CANCEL_HDMUAHANG
@MAHDMH char(20)
AS
BEGIN
DELETE FROM HDMUAHANG WHERE MAHDMH=@MAHDMH
END
GO

CREATE PROCEDURE TIM_HD
@MAHDMH char(20)
AS
BEGIN
SELECT HDMUAHANG.MAHDMH,HDMUAHANG.TENSP,HDMUAHANG.SOLUONG,HDMUAHANG.NGAYMUA,HDMUAHANG.NGUOIMUA,HDMUAHANG.GIA ,HDMUAHANG.TONG  FROM HDMUAHANG
WHERE HDMUAHANG.MAHDMH LIKE '%'+@MAHDMH+'%'
END
GO
-----------------------------------------------------------------------------------

CREATE TABLE THUE
(
MATHUE INT IDENTITY(1,1),
MAHD CHAR(20),
LOAITHUE NVARCHAR(100) NOT NULL,
TRANGTHAI NVARCHAR(20) NOT NULL,
TONGCHIPHI FLOAT DEFAULT 0 NOT NULL,
CONSTRAINT PK_MATHUE PRIMARY KEY(MATHUE),
CONSTRAINT FK_MAHDTHUE FOREIGN KEY(MAHD) REFERENCES HDBANHANG(MAHD)
)
INSERT INTO THUE VALUES ('HD01',N'Giá trị gia tăng','Đã nộp','300000');
INSERT INTO THUE VALUES ('HD02',N'Tiêu thụ đặt biệt','Chưa nộp','1000000');

GO

CREATE PROCEDURE LOAD_THUE
AS
BEGIN
SELECT * FROM THUE
END
GO

CREATE PROCEDURE INSERT_THUE
@MAHD CHAR(20),
@LOAITHUE NVARCHAR(100),
@TRANGTHAI NVARCHAR(20),
@TONGCHIPHI FLOAT
AS
BEGIN
INSERT INTO THUE(MAHD,LOAITHUE,TRANGTHAI,TONGCHIPHI) VALUES(@MAHD,@LOAITHUE,@TRANGTHAI,@TONGCHIPHI)
END
GO

CREATE PROCEDURE TIM_LOAITHUE
@LOAITHUE NVARCHAR(100)
AS
BEGIN
SELECT THUE.MATHUE,HDBANHANG.MAHD,THUE.LOAITHUE,THUE.TRANGTHAI,THUE.TONGCHIPHI FROM THUE INNER JOIN HDBANHANG ON THUE.MAHD=HDBANHANG.MAHD WHERE THUE.LOAITHUE LIKE '%'+@LOAITHUE+'%'
END
GO

--------------------------------------------------------[------------------

CREATE TABLE NHANVIEN
(
IDNV char(20),
TENNV NVARCHAR(100) NOT NULL,
NGAYSINH DATE NOT NULL,
SDT CHAR(12) NOT NULL,
GIOITINH NCHAR(3) NOT NULL
CONSTRAINT PK_IDNV PRIMARY KEY(IDNV)
)
insert into NHANVIEN values ('NV01',N'Trung Khải','07/11/2001','0336495005',N'Nam')
delete from NHANVIEN;
GO
CREATE PROCEDURE LOAD_NHANVIEN
AS
BEGIN
SELECT NHANVIEN.IDNV,NHANVIEN.TENNV,NHANVIEN.NGAYSINH,NHANVIEN.SDT,NHANVIEN.GIOITINH,TAIKHOAN.TENTK,TAIKHOAN.MATKHAU,TAIKHOAN.QUYEN
FROM NHANVIEN
inner join TAIKHOAN on NHANVIEN.IDNV=TAIKHOAN.IDNV
END
GO
CREATE PROCEDURE INSERT_NHANVIEN
@IDNV CHAR(20),@TENNV NVARCHAR(100), @NGAYSINH DATE,@SDT CHAR(12),@GIOITINH NCHAR(3)
AS
BEGIN
INSERT INTO NHANVIEN(IDNV,TENNV,NGAYSINH,SDT,GIOITINH) VALUES(@IDNV,@TENNV,@NGAYSINH,@SDT,@GIOITINH)
END
GO
CREATE PROCEDURE UPDATE_NHANVIEN
@IDNV char(20),@TENNV NVARCHAR(100),@NGAYSINH DATE,@SDT CHAR(20),@GIOITINH NCHAR(3)
AS
BEGIN
UPDATE NHANVIEN SET TENNV=@TENNV,NGAYSINH=@NGAYSINH,SDT=@SDT,GIOITINH=@GIOITINH WHERE IDNV=@IDNV
END
GO
CREATE PROCEDURE DELETE_NHANVIEN
@IDNV CHAR(20)
AS
BEGIN
DELETE FROM NHANVIEN WHERE IDNV=@IDNV
END
GO
CREATE PROCEDURE COUNT_NHANVIEN
AS
BEGIN
SELECT COUNT(*)+ABS(CHECKSUM(NewId())) % 1000 FROM NHANVIEN
END
GO
CREATE PROCEDURE TIM_TENNV
@TEN NVARCHAR(100)
AS
BEGIN
SELECT NHANVIEN.IDNV,NHANVIEN.TENNV,NHANVIEN.NGAYSINH,NHANVIEN.SDT,NHANVIEN.GIOITINH,TAIKHOAN.TENTK,TAIKHOAN.MATKHAU,TAIKHOAN.QUYEN
FROM NHANVIEN
inner join TAIKHOAN on NHANVIEN.IDNV=TAIKHOAN.IDNV
where NHANVIEN.TENNV like '%'+@TEN+'%'
END
GO

-------------------------------------------------------------------------------------

CREATE TABLE TAIKHOAN
(
TENTK VARCHAR(50),
MATKHAU VARCHAR(20) NOT NULL,
QUYEN VARCHAR(20) NOT NULL CHECK (QUYEN='NHANVIEN' OR QUYEN='ADMIN'),
IDNV char(20) NOT NULL,
CONSTRAINT PK_TENTK PRIMARY KEY(TENTK),
CONSTRAINT FK_MANVTK FOREIGN KEY(IDNV) REFERENCES NHANVIEN(IDNV)
)
insert into TAIKHOAN values ('admin','adminn','ADMIN','NV01')
GO

CREATE PROCEDURE LOAD_TAIKHOAN
AS
BEGIN
SELECT * FROM TAIKHOAN
END
GO

CREATE PROCEDURE INSERT_TAIKHOAN
@TENTK VARCHAR(50),@MATKHAU VARCHAR(20),@QUYEN VARCHAR(20),@IDNV char(20)
AS
BEGIN
INSERT INTO TAIKHOAN(TENTK,MATKHAU,QUYEN,IDNV) VALUES(@TENTK,@MATKHAU,@QUYEN,@IDNV)
END
GO

CREATE PROCEDURE UPDATE_TAIKHOAN
@TENTK VARCHAR(50),@MATKHAU VARCHAR(20),@QUYEN VARCHAR(20),@IDNV char(20)
AS
BEGIN
UPDATE TAIKHOAN SET MATKHAU=@MATKHAU,QUYEN=@QUYEN,IDNV=@IDNV WHERE TENTK=@TENTK
END
GO

CREATE PROCEDURE DELETE_TAIKHOAN
@TENTK VARCHAR(50)
AS
BEGIN
DELETE FROM TAIKHOAN WHERE TENTK=@TENTK
END
GO

CREATE PROCEDURE CHECK_TAIKHOAN
@TENTK VARCHAR(50),@MATKHAU VARCHAR(20)
AS
BEGIN
SELECT COUNT(*) FROM TAIKHOAN WHERE TAIKHOAN.TENTK=@TENTK AND TAIKHOAN.MATKHAU=@MATKHAU
END
GO

CREATE PROCEDURE GET_TENVAQUYEN_TAIKHOAN
@TENTK VARCHAR(50),@MATKHAU VARCHAR(20)
AS
BEGIN
SELECT TAIKHOAN.QUYEN,NHANVIEN.TENNV,NHANVIEN.IDNV
FROM TAIKHOAN 
INNER JOIN NHANVIEN ON TAIKHOAN.IDNV=NHANVIEN.IDNV
WHERE TAIKHOAN.TENTK=@TENTK AND TAIKHOAN.MATKHAU=@MATKHAU
END
GO

----------------------------------------------------------------------------------

CREATE TABLE KHO
(
MAKHO INT IDENTITY(1,1),
MASPMH char(20) NOT NULL,
TENSP NVARCHAR(100) NOT NULL,
SOLUONG INT NOT NULL,
CONSTRAINT PK_MAKHO PRIMARY KEY(MAKHO),
CONSTRAINT FK_MASPMHKHO FOREIGN KEY(MASPMH) REFERENCES MUAHANG(MASPMH)
)
INSERT INTO KHO VALUES ('SP01',N'Nhiên liệu','600');
INSERT INTO KHO VALUES ('SP02',N'Giấy','500');


GO

CREATE PROCEDURE LOAD_KHO
AS
BEGIN
SELECT * FROM KHO
END
GO

CREATE PROCEDURE INSERT_KHO
@MASPMH char(20),
@TENSP NVARCHAR(100),
@SOLUONG INT
AS
BEGIN
INSERT INTO KHO(MASPMH,TENSP,SOLUONG) VALUES(@MASPMH,@TENSP,@SOLUONG)
END
GO

CREATE PROCEDURE TIM_TENSP
@TENSP NVARCHAR(100)
AS
BEGIN
SELECT KHO.MAKHO,MUAHANG.MASPMH,KHO.TENSP,KHO.SOLUONG FROM KHO INNER JOIN MUAHANG ON KHO.MASPMH=MUAHANG.MASPMH WHERE KHO.TENSP LIKE '%'+@TENSP+'%'
END
GO

